/* GENERATED by src/sms/mktiles.py - edit the generator, not this file. */

#ifndef SMS_TILES_H
#define SMS_TILES_H

/* CoCo 3 sheet indices used by name (the rest are named in graphics.c) */
#define T_BLANK         0x20
#define T_SEA           0x18
#define T_HIT           0x19
#define T_MISS          0x1A
#define T_HIT2          0x1B
#define T_HIT_LEGEND    0x1C
#define T_CLOCK         0x1D
#define T_CONN_1        0x1E
#define T_CONN_2        0x1F
#define T_ATTACK_ANIM   0x63    /* 6 frames */
#define T_WATER         0x6B    /* 6 sparkle variants */

/* Made by the generator */
#define T_RULE          0x71
#define T_BADGE_BOT     0x72
#define T_BADGE_TOP     0x73
#define T_BULLET_BOT    0x74
#define T_BULLET_TOP    0x75
#define T_JOIN_LEFT     0x76
#define T_JOIN          0x77
#define T_JOIN_RIGHT    0x78

/* Fonts: tile = base + character - 0x20 */
#define NAME_BOT_BASE   0x080  /* $20-$5F, white on red-orange, strip below */
#define NAME_TOP_BASE   0x0C0  /* $20-$5F, white on red-orange, strip above */
#define TEXT_BASE       0x100  /* $20-$7F, colour 15 on black */
#define NAME_GLYPHS     64
#define TEXT_GLYPHS     96

/* Colour indices the fonts are expanded in */
#define C_BLACK         0
#define C_WHITE         3
#define C_BADGE         12
#define C_TEXT          15

extern const unsigned char sms_palette[32];
extern const unsigned char sms_tiles[];
extern const unsigned char sms_font[];

#endif /* SMS_TILES_H */
