#!/usr/bin/env bash
# build.sh -- assemble the Atari 2600 Battleship client.
#
# Output: build/battleship.bin, exactly 8192 bytes -- three 2K banks then the
# 2K fixed half, which is the layout vcs_set_image expects and one of the four
# sizes MAME's vcs_cart_slot_device::call_load() accepts.
#
#   bank 0  bslobby   pick a name, pick a table, join it
#   bank 1  bsgame    poll /state, show a board, attack
#   bank 2  bsplace   put your five ships down
#   fixed   bstail    the cold stub and the bank trampoline
#
# Each bank carries its OWN copy of bslib, net, url and the display kernel:
# the high 2K of the window is the cartridge's mailbox in its entirety, so
# there is no fixed code region to share one from. That is why those modules
# are guarded on BSBANK -- at 2048 bytes a bank, what a bank never calls is
# worth leaving out, and the play bank has nine bytes to spare.
#
# The "FUJI" claim is stamped into the fixed half; without it the cartridge
# treats the image as a game and the mailbox goes dead the moment it boots.
#
# Env:
#   ENDPOINT=...   the server (default https://battleship.carr-designs.com/)
#   FUJI_FIRMWARE=...  firmware tree (default ~/Workspace/fujinet-firmware)

set -euo pipefail
cd "$(dirname "$0")"

FUJI_FIRMWARE="${FUJI_FIRMWARE:-$HOME/Workspace/fujinet-firmware}"
VCS="$FUJI_FIRMWARE/pico/atari-2600"

if command -v asl >/dev/null 2>&1; then
    AS=asl P2BIN=p2bin
elif [ -x "$HOME/asl/asl" ]; then
    AS="$HOME/asl/asl" P2BIN="$HOME/asl/p2bin"
else
    echo "build.sh: no Macroassembler AS found (tried PATH and ~/asl)" >&2
    exit 1
fi

mkdir -p build

# The equates are hand-mirrored from the firmware header, so check them before
# assembling anything: a drifted address assembles cleanly, runs, and silently
# talks to a page that decodes nothing.
python3 tools/checkdefs.py "$VCS/firmware/include/fuji_mailbox.h" fujinet.inc

# Regenerated every run so a stale value cannot survive an environment change.
{
    echo "; generated by build.sh -- do not edit"
    printf 'UENDPT: DB      "%s"\n' "${ENDPOINT:-https://battleship.carr-designs.com/}"
    echo "        DB      0"
} > build/endpoint.inc

# p2bin ALWAYS emits the full -r range, so an over-long bank is truncated
# silently: the image builds, the size is right, checkrom passes, and the
# instructions past $17FF are simply gone. The assembler's own end address is
# the only thing that knows, so the build asks it.
bankfits() {
    local b=$1 end
    end=$(sed -nE 's|^ *[0-9]+/([0-9A-F]{4}) .*\bEND$|\1|p' "build/$b.lst" | tail -1)
    if [ -z "$end" ]; then
        echo "build.sh: cannot find $b's end address in its listing" >&2
        exit 1
    fi
    if [ $((0x$end)) -gt $((0x1800)) ]; then
        echo "build.sh: $b ends at \$$end, past \$1800 -- the bank is" >&2
        echo "  $(( 0x$end - 0x1800 )) bytes over and p2bin would truncate it" >&2
        exit 1
    fi
    printf '  %-9s $1000-$%s, %4d of 2048 bytes\n' "$b" "$end" $((0x$end - 0x1000))
}

parts=()
for b in bslobby bsgame bsplace; do
    $AS -q -L "$b.asm"
    mv "$b.p" "build/$b.p"
    mv -f "$b.lst" "build/$b.lst" 2>/dev/null || true
    bankfits "$b"
    $P2BIN "build/$b.p" "build/$b.bin" -r '$1000-$17FF' -l 0
    rm -f "build/$b.p"
    parts+=("build/$b.bin")
done
$AS -q -L bstail.asm
mv bstail.p build/bstail.p
mv -f bstail.lst build/bstail.lst 2>/dev/null || true
$P2BIN build/bstail.p build/bstail.bin -r '$1800-$1FFF' -l 0
rm -f build/bstail.p

cat "${parts[@]}" build/bstail.bin > build/battleship.bin
rm -f "${parts[@]}" build/bstail.bin

# The fixed half is the LAST 2K, so the claim's offset is
# (size - 2048) + (FN_R_CLAIM - $1800).
size=$(stat -c%s build/battleship.bin)
printf 'FUJI' | dd of=build/battleship.bin bs=1 \
    seek=$((size - 0x800 + 0x0710)) conv=notrunc status=none

python3 tools/checkrom.py build/battleship.bin
echo "build/battleship.bin: $size bytes"
