#!/usr/bin/env python3
"""mklayout.py -- the layout ROM's four boards, as playfield tables.

Writes build/layoutpf.inc: `ORG` + `DB` lines that put HIT/MID/AUX tables for
four slots at the plane bytes the kernel reads (fuji_mailbox.h, the playfield
board), so the layout ROM shows composed boards with no cartridge work at all.
tools/pfcheck.py imports PICTURE from here to read a snapshot back against it.

The picture, per slot, is ten rows of ten characters: '.' sea, 'X' hit,
'O' miss, '#' hull (AUX), '+' cursor (AUX), 'H' a hit on a hull (HIT|MID|AUX).
"""

import sys

T_BASE, PLANE_LEN, ROW0, KLEN, KINDS, DIM = 0x1800, 0x80, 30, 20, 3, 10
HIT, MID, AUX = 0, 1, 2
REG_OF = [0, 0, 1, 1, 1, 1, 2, 2, 2, 2]
BITS_OF = [0x30, 0xC0, 0xC0, 0x30, 0x0C, 0x03, 0x03, 0x0C, 0x30, 0xC0]

# Slot 0 top-left, 1 top-right, 2 bottom-left, 3 bottom-right. Every kind
# appears in every slot, the corners are exercised, and no two slots are the
# same picture, so a half or a pair drawn from the wrong table is visible.
PICTURE = [
    [   # slot 0: an enemy board with the cursor at (4,3)
        "X.........",
        ".X....O...",
        "..X.......",
        "...X+.....",
        "....X.....",
        "O....X....",
        "......X...",
        ".......X..",
        "........X.",
        "O........X",
    ],
    [   # slot 1: misses and a sunk-looking cluster
        "O.O.O.O.O.",
        ".O.O.O.O.O",
        "..........",
        "...XXXX...",
        "..........",
        "..........",
        "OOO...XXXX",
        "..........",
        "..........",
        "X........O",
    ],
    [   # slot 2: YOUR board: hulls, one of them hit
        "#####.....",
        "..........",
        "..#......O",
        "..#..HH#..",
        "..#.......",
        "..#.......",
        ".....O....",
        "..........",
        ".......##.",
        "O........X",
    ],
    [   # slot 3: nearly empty
        "..........",
        "..........",
        "..........",
        "..........",
        "..........",
        "..........",
        "..........",
        "..........",
        "..........",
        ".........X",
    ],
]


def kinds_of(ch):
    return {'.': (), 'X': (HIT, MID), 'O': (MID,), '#': (AUX,), '+': (AUX,),
            'H': (HIT, MID, AUX)}[ch]


def tables():
    """Return {plane offset: byte} for every table byte, all four slots."""
    out = {}
    for slot, pic in enumerate(PICTURE):
        half, pair = slot & 1, slot >> 1
        for kind in range(KINDS):
            for y in range(DIM):
                regs = [0, 0, 0]
                for x in range(DIM):
                    if kind in kinds_of(pic[y][x]):
                        regs[REG_OF[x]] |= BITS_OF[x]
                for r in range(3):
                    plane = r + 3 * half
                    off = plane * PLANE_LEN + ROW0 + kind * KLEN + pair * DIM + y
                    out[off] = regs[r]
    return out


def main():
    t = tables()
    print("; generated by tools/mklayout.py -- do not edit")
    for plane in range(6):
        base = plane * PLANE_LEN + ROW0
        print("        ORG     $%04X" % (T_BASE + base))
        row = [t.get(base + i, 0) for i in range(KINDS * KLEN)]
        for i in range(0, len(row), 20):
            print("        DB      " + ",".join("$%02X" % b for b in row[i:i+20]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
