#!/usr/bin/env python3
"""mkudc.py -- generate assets/udc.inc, the UDC bank for the client.

The 2637 UVI has 8 user-defined characters at $1980-$19BF (codes $38-$3F),
8 bytes each, bit 7 leftmost, and THE FIRST FOUR double as the sprite
images. Battleship uses exactly one sprite -- the targeting reticle -- so
slot $38 must hold that shape; the other seven are ordinary glyphs and
there is only ever one bank, loaded once at boot.

The board FRAMES are not here: they come from the 2637's built-in
graphics glyphs ($04-$0B are a complete box-drawing kit), which is what
leaves all eight UDCs for the battleship shapes.

Hull art is drawn edge-to-edge so adjacent segments tile into a
continuous ship; the caps round off the two ends. Every emitted byte
carries the row's art in the comment so the generated file reviews by eye.

Output is committed; regenerate with `make assets`.
"""

from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "assets" / "udc.inc"

# 8x8 art, '#' = ink.
GLYPHS = {
    # $38 -- sprite 0's image: corner brackets only. Deliberately hollow:
    # the reticle sits ON TOP of a board cell and must not hide whether
    # that cell is sea, a hit or a miss.
    "CURSOR": [
        "##....##",
        "#......#",
        "........",
        "........",
        "........",
        "........",
        "#......#",
        "##....##",
    ],
    # $39 -- horizontal hull midsection; full width so segments tile.
    "SHIPH": [
        "........",
        "........",
        "########",
        "########",
        "########",
        "########",
        "........",
        "........",
    ],
    # $3A -- vertical hull midsection; full height so segments tile.
    "SHIPV": [
        "..####..",
        "..####..",
        "..####..",
        "..####..",
        "..####..",
        "..####..",
        "..####..",
        "..####..",
    ],
    # $3B -- an end cap that reads at either orientation: a rounded blob
    # that meets a hull on every side.
    "SHIPE": [
        "........",
        "..####..",
        ".######.",
        ".######.",
        ".######.",
        ".######.",
        "..####..",
        "........",
    ],
    # $3C -- hit burst: a jagged star, drawn in red on the sea.
    "HIT": [
        "#..#..#.",
        ".#.#.#..",
        "..###...",
        "###.###.",
        "..###...",
        ".#.#.#..",
        "#..#..#.",
        "........",
    ],
    # $3D -- miss splash: a small open ring, deliberately light so a
    # field of misses does not read as damage.
    "MISS": [
        "........",
        "........",
        "..###...",
        "..#.#...",
        "..###...",
        "........",
        "........",
        "........",
    ],
    # $3E -- sunk: a wreck, hull broken open.
    "SUNK": [
        "........",
        "#......#",
        "##....##",
        "#.#..#.#",
        "#..##..#",
        "##....##",
        "#......#",
        "........",
    ],
    # $3F -- ship pip / placement cursor: a small filled block.
    "PIP": [
        "........",
        ".######.",
        ".#....#.",
        ".#....#.",
        ".#....#.",
        ".#....#.",
        ".######.",
        "........",
    ],
}

BANK = ["CURSOR", "SHIPH", "SHIPV", "SHIPE", "HIT", "MISS", "SUNK", "PIP"]


def rowbyte(row: str) -> int:
    assert len(row) == 8, row
    v = 0
    for i, ch in enumerate(row):
        assert ch in "#.", row
        if ch == "#":
            v |= 0x80 >> i
    return v


def main() -> None:
    for name, art in GLYPHS.items():
        assert len(art) == 8, name

    lines = [
        "; udc.inc -- generated by tools/mkudc.py; do not edit.",
        ";",
        "; The 64-byte UDC bank for $1980-$19BF (glyph codes $38-$3F). Slot",
        "; $38 is also sprite 0's image, which is why the targeting reticle",
        "; lives there. Loaded once at boot by UDCLD below (page-1 code: the",
        "; data is in block 2, the UDC RAM is page 0, so the copy runs",
        "; through the PUDC pointer).",
        "",
        "UDCBK:",
    ]
    total = 0
    for slot, name in enumerate(BANK):
        lines.append(f"; ${0x38 + slot:02X} {name}")
        for row in GLYPHS[name]:
            b = rowbyte(row)
            lines.append(f"        DB      %{b:08b}        ; {row}")
            total += 1
    lines.append("")

    lines.append("""\
; UDCLD: load the bank into the UDC RAM. Page-1 code; clobbers R0,R3.
UDCLD:  LODI,R3 63
UDCL1:  LODA,R0 UDCBK,R3
        STRA,R0 *PUDC,R3
        BDRR,R3 UDCL1
        LODA,R0 UDCBK
        STRA,R0 *PUDC
        RETC,UN

PUDC:   DWBE    UDC
""")

    assert total == 64, total
    OUT.write_text("\n".join(lines))
    print(f"{OUT}: {total} bytes of UDC art")


if __name__ == "__main__":
    main()
